apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springdemoapp
  name: springdemoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springdemoapp
  template:
    metadata:
      labels:
        app: springdemoapp
    spec:
      containers:
      - name: myapp
        image: moezg/springboot:3
        ports:
        - containerPort: 8080
