apiVersion: v1
kind: Service
metadata:
  name: springdemoapp-service
spec:
  type: NodePort
  selector:
    app: springdemoapp
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 8080
    targetPort: 8080